catalog/urls.py
from django.contrib import admin
from django.urls import path
from app.views import CarList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CarList.as_view(), name='index'),
]

app/models.py
from django.db import models


class Car(models.Model):

    manufacturer = models.CharField(max_length=20)
    model = models.CharField(max_length=10)
    year = models.IntegerField()
    transmission = models.SmallIntegerField(choices=[(1, 'manual'), (2, 'automatic'), (3, 'robot')])
    color = models.CharField(max_length=10)


    def __str__(self):

        return self.manufacturer + ' ' + self.model

app/forms.py
from django import forms


class CarForm(forms.Form):
    manufacturer = forms.CharField(max_length=20, required=False)
    model = forms.CharField(max_length=10, required=False)
    year = forms.IntegerField(required=False)
    transmission = forms.MultipleChoiceField(choices=[(1, 'manual'), (2, 'automatic'), (3, 'robot')], required=False)
    color = forms.CharField(max_length=10, required=False)

app/views.py
from django.db.models import Q
from app.models import Car
from app.forms import CarForm

from django.views.generic import ListView



class CarList(ListView):
    model = Car
    template_name = 'index.html'
    form_class = CarForm


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = self.get_queryset()
        context['form'] = self.form_class
        return context


    def get_queryset(self):
        qs = self.model.objects.all()
        manufacturer = self.request.GET.get('manufacturer')
        model = self.request.GET.get('model')
        year = self.request.GET.get('year')
        transmission = self.request.GET.get('transmission')
        color = self.request.GET.get('color')
        if manufacturer:
            qs = qs.filter(manufacturer=manufacturer)
        if model:
            qs = qs.filter(model=model)
        if year:
            qs = qs.filter(year=year)
        if transmission:
            qs = qs.filter(transmission=transmission)
        if color:
            qs = qs.filter(color=color)
        return qs

app/templates/index.html
<!DOCTYPE html>
    <head>
        <title>Catalog</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <br>
            <form method='get'>
                
                {{ form.as_ul }}
                <input type='submit' value='Filter'>
            </form>
            <br>
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Производитель</th>
                        <th scope="col">Модель</th>
                        <th scope="col">Год выпуска</th>
                        <th scope="col">Коробка передач</th>
                        <th scope="col">Цвет</th>
                    </tr>
                </thead>
                {% for car in cars %} 
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ car.manufacturer }}</td>
                    <td>{{ car.model }}</td>
                    <td>{{ car.year }}</td>
                    <td>{{ car.get_transmission_display }}</td>
                    <td>{{ car.color }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </body>
</html>